version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root directory
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/brobot" # Directory to ignore
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
